name: json2ciw
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.5.1
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.10.8
  - numpy=2.4.0
  - pandas=2.3.3
  - pip=25.3
  - python=3.12
  - pip:
    - ciw==3.2.7
